draw_set_font(font_large_hud)
draw_text_shadow_color(6,4,"Ye' Ole Credits",c_white,c_white,c_silver,c_silver)
draw_line_colour(6,48,365,48,c_white,c_silver)
draw_line_colour(6,49,365,49,c_white,c_silver)

draw_line_colour(6,51,364,51,c_white,c_silver)
draw_line_colour(6,52,360,52,c_silver,c_silver)

draw_set_font(font_stats)
draw_text_shadow_color(316,180,"Created & Developed by Pj Chavez",c_white,c_white,c_white,c_white)
draw_text_shadow_color(316,210,"Special thanks to Discord & Reddit community!",c_white,c_white,c_white,c_white)
draw_text_shadow_color(316,240,"Pixel Art by Stacube",c_white,c_white,c_white,c_white)
draw_text_shadow_color(316,270,"Pixel Art by SquareAddict",c_white,c_white,c_white,c_white)
draw_text_shadow_color(316,300,"Pixel Art by Zedotagger",c_white,c_white,c_white,c_white)
draw_text_shadow_color(316,330,"NPC Art by Jesse Munguia",c_white,c_white,c_white,c_white)
draw_text_shadow_color(316,360,"NPC Art by William Robinson",c_white,c_white,c_white,c_white)
draw_text_shadow_color(316,390,"NPC Art by Luiz Meo",c_white,c_white,c_white,c_white)
draw_text_shadow_color(316,420,"Music by The Other User",c_white,c_white,c_white,c_white)
draw_text_shadow_color(316,450,"Music by Wanderlust Sparkles",c_white,c_white,c_white,c_white)
draw_text_shadow_color(316,480,"Music by Ambient Melodia",c_white,c_white,c_white,c_white)
draw_text_shadow_color(316,510,"Music by JL",c_white,c_white,c_white,c_white)
draw_text_shadow_color(316,540,"Music by Gitoro",c_white,c_white,c_white,c_white)
draw_text_shadow_color(316,570,"Music by Slamma",c_white,c_white,c_white,c_white)
draw_text_shadow_color(316,600,"Motivation by Chris Zukowski",c_white,c_white,c_white,c_white)